application:
  name: eiji
  project: eiji
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
  - type: postgresql
    version: "12.6"
    name: eiji
routers:
  - name: main
    routes:
      - application_name: eiji
        paths:
          - /
